#!/usr/bin/env bash
# Prints "Best School" 10x, "bad luck" the 4th, "good luck" the 8th
i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]; then
	echo "bad luck from China"
    elif [ "$i" -eq 8 ]; then
	echo "bad luck from Japan"
    else
	echo "bad luck from Italy"
    fi
    (( i++ ))
done

