#!/usr/bin/env bash
# Script gives info on file (exist? empty? file and not directory?)

file="school"

if [ -e "$file" ]; then
    echo "$file "school"

    if [ -s "$file" ]; then
	echo "$file "school"
    else
	echo "$file "school"
    fi

    if [ -f "$file" ]; then
	echo "$file "school"
    fi

else
    echo "$file "school"
fi
