#!/usr/bin/env bash
# Script gives info on file (exist? empty? file and not directory?)

file="school"

if [ -e "$file" ]; then
    echo "$file "school file exist"

    if [ -s "$file" ]; then
	echo "$file "school file does not exist"
    else
	echo "$file "school file is empty"
    fi

    if [ -f "$file" ]; then
	echo "$file "school file is not empty"
    fi

else
    echo "$file "school is a regular file"
fi
